name: CI/CD Development Pipeline

on:
  push:
    branches:
      - main
      - "feature/**"
  pull_request:
    branches:
      - main

jobs:
  # --- Microservicio Vote (Java) ---
  built-vote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Vote
        uses: docker/build-push-action@v5
        with:
          context: ./vote
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/voting-app-vote:latest
            ${{ secrets.DOCKER_USERNAME }}/voting-app-vote:${{ github.sha }}

  # --- Microservicio Worker (GO) ---
  build-worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Worker
        uses: docker/build-push-action@v5
        with:
          context: ./worker
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/voting-app-worker:latest
            ${{ secrets.DOCKER_USERNAME }}/voting-app-worker:${{ github.sha }}

  # --- Microservicio Result (Node.js) ---
  build-result:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Result
        uses: docker/build-push-action@v5
        with:
          context: ./result
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/voting-app-result:latest
            ${{ secrets.DOCKER_USERNAME }}/voting-app-result:${{ github.sha }}
